/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikkum190625;

/**
 *
 * @author asus
 */
public class menuMinuman extends javax.swing.JFrame {

     private menuUtama utama;
    
    public menuMinuman() {
        initComponents();
    }
     public menuMinuman(menuUtama utama){
        this.utama =utama;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        chkMatcha = new javax.swing.JCheckBox();
        chkAir = new javax.swing.JCheckBox();
        chkThai = new javax.swing.JCheckBox();
        chkGreen = new javax.swing.JCheckBox();
        txtMatcha = new javax.swing.JTextField();
        txtAir = new javax.swing.JTextField();
        txtThai = new javax.swing.JTextField();
        txtGreen = new javax.swing.JTextField();
        cbMatcha = new javax.swing.JComboBox<>();
        cbAir = new javax.swing.JComboBox<>();
        cbGreen = new javax.swing.JComboBox<>();
        cbThai = new javax.swing.JComboBox<>();
        txtTotalMatcha = new javax.swing.JTextField();
        txtTotalAir = new javax.swing.JTextField();
        txtTotalThai = new javax.swing.JTextField();
        txtTotalGreen = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTotalHarga = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR MENU MINUMAN");

        chkMatcha.setText("Matcha Latte");
        chkMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMatchaActionPerformed(evt);
            }
        });

        chkAir.setText("Air Mineral");
        chkAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAirActionPerformed(evt);
            }
        });

        chkThai.setText("Thai tea");
        chkThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkThaiActionPerformed(evt);
            }
        });

        chkGreen.setText("Green Tea");
        chkGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGreenActionPerformed(evt);
            }
        });

        txtMatcha.setText("0");
        txtMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatchaActionPerformed(evt);
            }
        });

        txtAir.setText("0");
        txtAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirActionPerformed(evt);
            }
        });

        txtThai.setText("0");
        txtThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThaiActionPerformed(evt);
            }
        });

        txtGreen.setText("0");
        txtGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGreenActionPerformed(evt);
            }
        });

        cbMatcha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatchaActionPerformed(evt);
            }
        });

        cbAir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirActionPerformed(evt);
            }
        });

        cbGreen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGreenActionPerformed(evt);
            }
        });

        cbThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThaiActionPerformed(evt);
            }
        });

        txtTotalMatcha.setText("0");
        txtTotalMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMatchaActionPerformed(evt);
            }
        });

        txtTotalAir.setText("0");
        txtTotalAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAirActionPerformed(evt);
            }
        });

        txtTotalThai.setText("0");
        txtTotalThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalThaiActionPerformed(evt);
            }
        });

        txtTotalGreen.setText("0");

        txtTotalHarga.setText("0");
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali Ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMatcha)
                            .addComponent(chkThai)
                            .addComponent(chkGreen)
                            .addComponent(chkAir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset)
                                    .addComponent(txtThai, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(txtTotalMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnTotalHarga))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalThai, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtTotalGreen)
                                    .addComponent(txtTotalHarga)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalAir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMatcha)
                    .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAir)
                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkThai)
                    .addComponent(txtThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGreen)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset)
                    .addComponent(btnTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGreenActionPerformed

    private void chkMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMatchaActionPerformed
        txtMatcha.setText("20000");
    }//GEN-LAST:event_chkMatchaActionPerformed

    private void txtAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirActionPerformed

    private void txtTotalAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAirActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void chkAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirActionPerformed
        txtAir.setText("5000");
    }//GEN-LAST:event_chkAirActionPerformed

    private void chkThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkThaiActionPerformed
        txtThai.setText("15000");
    }//GEN-LAST:event_chkThaiActionPerformed

    private void chkGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGreenActionPerformed
        txtGreen.setText("22000");
    }//GEN-LAST:event_chkGreenActionPerformed

    private void cbMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatchaActionPerformed
        int jml = (int)cbMatcha.getSelectedIndex();
        double harga = Double.parseDouble(txtMatcha.getText());
        double total = jml*harga;
        txtTotalMatcha.setText(Double.toString(total));
    }//GEN-LAST:event_cbMatchaActionPerformed

    private void cbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirActionPerformed
        int jml = (int)cbAir.getSelectedIndex();
        double harga = Double.parseDouble(txtAir.getText());
        double total = jml*harga;
        txtTotalAir.setText(Double.toString(total));
    }//GEN-LAST:event_cbAirActionPerformed

    private void cbThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThaiActionPerformed
        int jml = (int)cbThai.getSelectedIndex();
        double harga = Double.parseDouble(txtThai.getText());
        double total = jml*harga;
        txtTotalThai.setText(Double.toString(total));
    }//GEN-LAST:event_cbThaiActionPerformed

    private void cbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGreenActionPerformed
        int jml = (int)cbGreen.getSelectedIndex();
        double harga = Double.parseDouble(txtGreen.getText());
        double total = jml*harga;
        txtTotalGreen.setText(Double.toString(total));
    }//GEN-LAST:event_cbGreenActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtMatcha.setText("0");
       txtAir.setText("0");
       txtThai.setText("0");
       txtGreen.setText("0");
       cbMatcha.setSelectedIndex(0);
       cbAir.setSelectedIndex(0);
       cbThai.setSelectedIndex(0);
       cbGreen.setSelectedIndex(0);
       txtTotalHarga.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
       double matcha = Double.parseDouble(txtTotalMatcha.getText());
        double air = Double.parseDouble(txtTotalAir.getText());
        double thai = Double.parseDouble(txtTotalThai.getText());
        double green = Double.parseDouble(txtTotalGreen.getText());
      
        double total = matcha+air+thai+green;
        txtTotalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalHarga.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtTotalThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalThaiActionPerformed

    private void txtTotalMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMatchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMatchaActionPerformed

    private void txtThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThaiActionPerformed

    private void txtMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatchaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbAir;
    private javax.swing.JComboBox<String> cbGreen;
    private javax.swing.JComboBox<String> cbMatcha;
    private javax.swing.JComboBox<String> cbThai;
    private javax.swing.JCheckBox chkAir;
    private javax.swing.JCheckBox chkGreen;
    private javax.swing.JCheckBox chkMatcha;
    private javax.swing.JCheckBox chkThai;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtGreen;
    private javax.swing.JTextField txtMatcha;
    private javax.swing.JTextField txtThai;
    private javax.swing.JTextField txtTotalAir;
    private javax.swing.JTextField txtTotalGreen;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMatcha;
    private javax.swing.JTextField txtTotalThai;
    // End of variables declaration//GEN-END:variables
}
