/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikkum190625;

/**
 *
 * @author asus
 */
public class menuMakanan extends javax.swing.JFrame {

    private menuUtama utama;
    
    public menuMakanan() {
        initComponents();
    }
    public menuMakanan(menuUtama utama){
        this.utama =utama;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkBakso = new javax.swing.JCheckBox();
        chkSerabi = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        chkMieAyam = new javax.swing.JCheckBox();
        txtBakso = new javax.swing.JTextField();
        txtSerabi = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        txtMieAyam = new javax.swing.JTextField();
        cbBakso = new javax.swing.JComboBox<>();
        cbSerabi = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        cbMieAyam = new javax.swing.JComboBox<>();
        txtTotalBakso = new javax.swing.JTextField();
        txtTotalSerabi = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        txtTotalMieAyam = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnTotalHarga = new javax.swing.JButton();
        txtTotalHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR MENU MAKANAN");

        chkBakso.setText("Bakso");
        chkBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBaksoActionPerformed(evt);
            }
        });

        chkSerabi.setText("Serabi");
        chkSerabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSerabiActionPerformed(evt);
            }
        });

        chkSoto.setText("Soto");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkMieAyam.setText("Mie Ayam");
        chkMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieAyamActionPerformed(evt);
            }
        });

        txtBakso.setText("0");
        txtBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaksoActionPerformed(evt);
            }
        });

        txtSerabi.setText("0");

        txtSoto.setText("0");

        txtMieAyam.setText("0");
        txtMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMieAyamActionPerformed(evt);
            }
        });

        cbBakso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaksoActionPerformed(evt);
            }
        });

        cbSerabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbSerabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerabiActionPerformed(evt);
            }
        });

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSotoActionPerformed(evt);
            }
        });

        cbMieAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieAyamActionPerformed(evt);
            }
        });

        txtTotalBakso.setText("0");
        txtTotalBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBaksoActionPerformed(evt);
            }
        });

        txtTotalSerabi.setText("0");
        txtTotalSerabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSerabiActionPerformed(evt);
            }
        });

        txtTotalSoto.setText("0");

        txtTotalMieAyam.setText("0");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali Ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        txtTotalHarga.setText("0");
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMieAyam)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSerabi)
                                    .addComponent(chkBakso)
                                    .addComponent(chkSoto))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSerabi)
                                            .addComponent(txtBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnReset))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSerabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalBakso)
                                    .addComponent(txtTotalSerabi)
                                    .addComponent(txtTotalSoto)
                                    .addComponent(txtTotalMieAyam)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBakso)
                            .addComponent(txtBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSerabi)
                            .addComponent(txtSerabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSerabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSerabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkSoto))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(chkMieAyam)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalHarga)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(58, 58, 58)
                .addComponent(btnKembali)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMieAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMieAyamActionPerformed

    private void chkBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBaksoActionPerformed
        txtBakso.setText("17000");
    }//GEN-LAST:event_chkBaksoActionPerformed

    private void cbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBaksoActionPerformed
        int jml = (int)cbBakso.getSelectedIndex();
        double harga = Double.parseDouble(txtBakso.getText());
        double total = jml*harga;
        txtTotalBakso.setText(Double.toString(total));
    }//GEN-LAST:event_cbBaksoActionPerformed

    private void chkSerabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSerabiActionPerformed
        txtSerabi.setText("20000");
    }//GEN-LAST:event_chkSerabiActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
       txtSoto.setText("15000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieAyamActionPerformed
        txtMieAyam.setText("17000");
    }//GEN-LAST:event_chkMieAyamActionPerformed

    private void cbSerabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerabiActionPerformed
       int jml = (int)cbSerabi.getSelectedIndex();
        double harga = Double.parseDouble(txtSerabi.getText());
        double total = jml*harga;
        txtTotalSerabi.setText(Double.toString(total));
    }//GEN-LAST:event_cbSerabiActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        int jml = (int)cbSoto.getSelectedIndex();
        double harga = Double.parseDouble(txtSoto.getText());
        double total = jml*harga;
        txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void cbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieAyamActionPerformed
        int jml = (int)cbMieAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtMieAyam.getText());
        double total = jml*harga;
        txtTotalMieAyam.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieAyamActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtBakso.setText("0");
       txtSerabi.setText("0");
       txtSoto.setText("0");
       txtMieAyam.setText("0");
       cbBakso.setSelectedIndex(0);
       cbSerabi.setSelectedIndex(0);
       cbSoto.setSelectedIndex(0);
       cbMieAyam.setSelectedIndex(0);
       txtTotalHarga.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        double bakso = Double.parseDouble(txtTotalBakso.getText());
        double serabi = Double.parseDouble(txtTotalSerabi.getText());
        double soto = Double.parseDouble(txtTotalSoto.getText());
        double MieAyam = Double.parseDouble(txtTotalMieAyam.getText());
      
        double total = bakso+serabi+soto+MieAyam;
        txtTotalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void txtTotalSerabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSerabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSerabiActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalHarga.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaksoActionPerformed

    private void txtTotalBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBaksoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbBakso;
    private javax.swing.JComboBox<String> cbMieAyam;
    private javax.swing.JComboBox<String> cbSerabi;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkBakso;
    private javax.swing.JCheckBox chkMieAyam;
    private javax.swing.JCheckBox chkSerabi;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBakso;
    private javax.swing.JTextField txtMieAyam;
    private javax.swing.JTextField txtSerabi;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotalBakso;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMieAyam;
    private javax.swing.JTextField txtTotalSerabi;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables
}
